cors:
  originPatterns: http://localhost:8090,https://erudio.com.br,http://localhost:3000
security:
  jwt:
    token:
      secret-key: 53ccr37
      expire-length: 3600000
server:
  port : 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: Jazz!Skull15
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view : false
spring-doc:
  pathsToMathch: /api/**/v1/**
  swagger-ui:
    use-root-path: true